#!/usr/bin/env python3
"""Pre-render reel narration with a studio TTS voice.

The app narrates reels with the device's speech engine, which is free and
offline but sounds like a device. This renders each step's `audioScript` once
with OpenAI's TTS and ships the mp3 with the app, so everyone hears the good
voice; the device engine remains the fallback for reels generated after the
last audio run.

Also writes a Metro-compatible manifest (static `require()` calls — Metro
cannot resolve dynamic asset paths), which the player imports.

Idempotent: existing clips are skipped, so a scheduled run only pays for new
steps. Cost is ~$0.015 per 1K characters (gpt-4o-mini-tts); a 6-step reel with
~400-char scripts is about 4 cents.

    python generate_audio.py --reels ../LeetSwipe/assets/data/reels.json \
        --out ../LeetSwipe/assets/audio
"""
from __future__ import annotations

import argparse
import json
import os
import sys

MODEL = "gpt-4o-mini-tts"
# 'nova' is the clear, energetic one — right register for short explainers.
VOICE = "nova"

MANIFEST_HEADER = """\
/**
 * GENERATED by backend_question_generation/generate_audio.py — do not edit.
 *
 * Maps reelId -> stepNumber -> a bundled studio-voice narration clip. Metro
 * resolves assets only through static require() calls, which is why this file
 * is generated code rather than a JSON lookup.
 */
/* eslint-disable @typescript-eslint/no-require-imports */

export const reelAudio: Record<string, Record<number, number>> = {
"""


def load_reels(path: str) -> list[dict]:
    with open(path, encoding="utf-8") as f:
        return json.load(f).get("reels", [])


def clip_path(out_dir: str, reel_id: str, step: int) -> str:
    return os.path.join(out_dir, reel_id, f"{step}.mp3")


def synthesise(client, text: str, dest: str) -> None:
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    with client.audio.speech.with_streaming_response.create(
        model=MODEL, voice=VOICE, input=text, response_format="mp3",
    ) as response:
        response.stream_to_file(dest)


def write_manifest(out_dir: str, reels: list[dict]) -> int:
    """Emit manifest.ts listing every clip that exists on disk."""
    lines = [MANIFEST_HEADER]
    total = 0
    for reel in reels:
        reel_id = str(reel.get("reelId", ""))
        entries = []
        for step in reel.get("steps", []):
            n = int(step.get("stepNumber", 0))
            if os.path.exists(clip_path(out_dir, reel_id, n)):
                entries.append(f"    {n}: require('./{reel_id}/{n}.mp3'),")
                total += 1
        if entries:
            lines.append(f"  '{reel_id}': {{")
            lines.extend(entries)
            lines.append("  },")
    lines.append("};\n")
    with open(os.path.join(out_dir, "manifest.ts"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return total


def main() -> int:
    ap = argparse.ArgumentParser(description="Render reel narration to mp3 via OpenAI TTS.")
    ap.add_argument("--reels", default="../LeetSwipe/assets/data/reels.json")
    ap.add_argument("--out", default="../LeetSwipe/assets/audio")
    ap.add_argument("--limit", type=int, default=0, help="Max clips to synthesise this run (0 = all missing).")
    ap.add_argument("--manifest-only", action="store_true",
                    help="Rebuild manifest.ts from clips already on disk; no API calls.")
    args = ap.parse_args()

    reels = load_reels(args.reels)
    if not reels:
        print("No reels found; nothing to do.")
        return 0

    if not args.manifest_only:
        from dotenv import load_dotenv
        load_dotenv()
        if not os.environ.get("OPENAI_API_KEY"):
            print("! OPENAI_API_KEY not set — cannot synthesise. "
                  "Use --manifest-only to rebuild the manifest without it.", file=sys.stderr)
            return 2
        from openai import OpenAI
        client = OpenAI()

        made = skipped = failed = 0
        chars = 0
        for reel in reels:
            reel_id = str(reel.get("reelId", ""))
            for step in reel.get("steps", []):
                n = int(step.get("stepNumber", 0))
                dest = clip_path(args.out, reel_id, n)
                if os.path.exists(dest):
                    skipped += 1
                    continue
                if args.limit and made >= args.limit:
                    continue
                script = str(step.get("audioScript", "")).strip()
                if not script:
                    continue
                try:
                    synthesise(client, script, dest)
                    made += 1
                    chars += len(script)
                    print(f"  + {reel_id}/{n}.mp3 ({len(script)} chars)")
                except Exception as e:  # keep going; fallback TTS covers gaps
                    failed += 1
                    print(f"  ! {reel_id}/{n}: {e}", file=sys.stderr)
        print(f"synthesised {made}, skipped {skipped} existing, {failed} failed "
              f"· ~${chars / 1000 * 0.015:.3f} spent")
        if made == 0 and failed > 0:
            return 1

    total = write_manifest(args.out, reels)
    print(f"manifest.ts: {total} clips listed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
