/**
 * GENERATED by backend_question_generation/generate_audio.py — do not edit.
 *
 * Maps reelId -> stepNumber -> a bundled studio-voice narration clip. Metro
 * resolves assets only through static require() calls, which is why this file
 * is generated code rather than a JSON lookup.
 */
/* eslint-disable @typescript-eslint/no-require-imports */

export const reelAudio: Record<string, Record<number, number>> = {

};
